# SITE SETTINGS
title: Camtrap DP
author: Camtrap DP Development Team
url: "https://camtrap-dp.tdwg.org"

# SOCIAL PROFILES
social:
  github: tdwg/camtrap-dp

# THEME SETTINGS
theme: minima
remote_theme: tdwg/petridish
github_edit: true
logo: /assets/theme/images/tdwg-logo-short.svg

# BUILD SETTINGS
# The repository contains symlinks and therefore requires GitHub Actions to build the website
# See https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error
repository: tdwg/camtrap-dp # Required so Jekyll on GitHub Actions can access repo metadata
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - example/*.csv
  - example/*.json
  - tests/*
  - "*.json"
  - vendor # Avoids https://github.com/jekyll/jekyll/issues/2938

# FRONTMATTER DEFAULTS
defaults:
  - scope:
      path: pages/example
    values:
      permalink: "/example/:basename/"
      layout: example
      title: Example dataset
      toc: true
